name: CI/CD .NET Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: seuusuario/meuapp-dotnet

    steps:
      # 1️⃣ Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      # 3️⃣ Restore dependências
      - name: Restore dependencies
        run: dotnet restore

      # 4️⃣ Build
      - name: Build
        run: dotnet build --configuration Release --no-restore

      # 5️⃣ Testes (opcional)
      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      # 6️⃣ Publish
      - name: Publish
        run: dotnet publish -c Release -o ./publish

      # 7️⃣ Login Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 8️⃣ Build Docker image
      - name: Build Docker image
        run: docker build -t $DOCKER_IMAGE:latest .

      # 9️⃣ Push Docker image
      - name: Push Docker image
        run: docker push $DOCKER_IMAGE:latest
